# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-23 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('auth.user',),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.Staff'),
        ),
    ]
